name: "web-tpl"
http:
   listen: "8080"
log:
  level: "debug"

redis:
    default:
      write:
        addr: "127.0.0.1:6379"
        password: ""
        pool_size: 10
        idle_timeout: "5000ms"
        read_timeout: "3000ms"
        write_timeout: "3000ms"
        min_idle_conns: 5
        retries: 3
        db: 0
      read:
        addr: "127.0.0.1:6379"
        password: ""
        pool_size: 10
        idle_timeout: "5000ms"
        read_timeout: "3000ms"
        write_timeout: "3000ms"
        min_idle_conns: 5
        retries: 3
        db: 0
db:
    default:
     log:
      enable: true
      level: "warning"
      format: "text" # json or text
      type: "stdout" #stdout or file
      path: "logs/app.log"
     write:
        host: "127.0.0.1"
        port: "3306"
        database: "kbh"
        username: "root"
        password: "123456"
        charset: "utf8mb4"
        timeout: 5000
        write_time_out: 5000  #
        read_time_out: 5000  #
        max_idle_conns: 5  #
        max_open_conns: 1000  #
     read:
        host: ""
        port: "3306"
        database: ""
        username: ""
        password: ""
        charset: "utf8mb4"
        timeout: 5000
        write_time_out: 5000  #
        read_time_out: 5000  #
        max_idle_conns: 5  #
        max_open_conns: 1000  #
    user:
      write:
        host: ""
        port: "3306"
        database: ""
        username: ""
        password: ""
        charset: "utf8mb4"
        timeout: 5000
        write_time_out: 5000  #
        read_time_out: 5000  #
        max_idle_conns: 5  #
        max_open_conns: 1000  #
      read:
        host: ""
        port: "3306"
        database: ""
        username: ""
        password: ""
        charset: "utf8mb4"
        timeout: 5000
        write_time_out: 5000  #
        read_time_out: 5000  #
        max_idle_conns: 5  #
        max_open_conns: 1000  #